apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-monitor
  labels:
    app: dns-throttle-monitor
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list"]
