apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-autoscaler
  namespace: kube-system
  labels:
    app: dns-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-autoscaler
  template:
    metadata:
      labels:
        app: dns-autoscaler
    spec:
      serviceAccountName: dns-autoscaler
      containers:
      - name: autoscaler
        image: registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.9
        command:
        - /cluster-proportional-autoscaler
        - --namespace=kube-system
        - --configmap=dns-autoscaler
        - --target=deployment/coredns
        - --default-params={"linear":{"coresPerReplica":256,"nodesPerReplica":16,"min":2,"max":10}}
        - --logtostderr=true
        - --v=2
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      nodeSelector:
        kubernetes.io/os: linux
